package com.vegeexpress.server;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.vegeexpress.server.model.Catalog;

@Controller // This means that this class is a Controller
@RequestMapping(path="/catalog") // This means URL's start with /demo (after Application path)
public class CatalogController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private CatalogRepository catalogRepo;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewCatalogItem (@RequestBody Catalog catalog) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    catalogRepo.save(catalog);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Catalog> getAllCatalogItems() {
    // This returns a JSON or XML with the users
    return catalogRepo.findAll();
  }
}